name: Run tests

on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # tag=v3.5.3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # tag=v4.0.1
        with:
          go-version-file: "go.mod"
          cache: true

      - name: Build
        run: |
          make build

      - name: Test
        run: |
          make test

      - name: Lint
        run: |
          make lint
